### ISSUE TITLE
npm install 404ing

### ISSUE THREAD

**Issue by sraje** [yanwsh/videojs-panorama#1]
Hey there, I tried to install the plugin using the following command: 
`npm install --save videojs-panorama`
and received a 404 from https://registry.npmjs.org/videojs-panorama and an error that said the plugin hasn't been registered.

**Comment by yanwsh** [comment]
hello,

Try it again, please. I should be fine now.

I also updated the documentation to help you set up this plugin. You can also check the live demo [here](http://yanwsh.github.io/videojs-panorama/).

Let me know if you have any questions.

Happy coding.

**Comment by sraje** [comment]
thanks!
