### ISSUE TITLE
Add text.hotpot to the video

### ISSUE THREAD

**Issue by srikanthima** [yanwsh/videojs-panorama#108]
Hi,

I need to know if there is an option to add text/hotspot to the video?

Regards

**Comment by yanwsh** [comment]
Hey, for text, you can add it directly to the video dom, like the notice message which show at the beginning of demo video.

For hotspot, i am planing to add it. But don't have option right now.

**Comment by srikanthima** [comment]
Hi,

We want the text also to scroll along with the video itself. i.e it should hold its coordinates relative to teh video. Like it should appear as it is a part of the video. Can you please give me a syntax of how to add this?

Regards

**Comment by yanwsh** [comment]
Hey, could you give me your email address, i can give you example, but for some reason, i can't put the link in public.

**Comment by srikanthima** [comment]
Hi,

srikanth.ch2008@gmail.com

Thanks
