### ISSUE TITLE
Hi, I want to get Latitude and Longitude in panorama.

### ISSUE THREAD

**Issue by Saydous** [yanwsh/videojs-panorama#11]
Hi, my name is Joogon and I'm reaaaaaaaaaaally appreciate for this plugin.
I use this in my player and all of things are good.
However, it's too hard to get latitude and longitude.
I want to do that give two values simultaneously and real time.
Can you make it in options or etc...?
Thx.

**Comment by yanwsh** [comment]
Hello, here's the code which you can get those two values.

```javascript
player.on("play", function () {
   var canvas = player.getChild('Canvas');
   canvas.lot;
   canvas.lat;
}
//or you can get the lon and lat on time updated.

player.on('timeupdate', function () {
   var canvas = player.getChild('Canvas');
   canvas.lot;
   canvas.lat;
});
```

**Comment by Saydous** [comment]
Good! Everything what I want to do is perfect!
Thanks a lot.
