### ISSUE TITLE
auto play video on mobile

### ISSUE THREAD

**Issue by tandaovan** [yanwsh/videojs-panorama#113]
Hi guys,

I want to automatically play the video on mobile. Currently i had to click on play button to play video.

thanks so much

**Comment by mmartain** [comment]
I don't think that is possible. At least on iOS Apple won't allow it trough javascript, so manual action is always required...

**Comment by yanwsh** [comment]
That's not true, on ios 10 and chrome 53, it supports video autoplay, you have to make sure add autoplay, muted and playsinline attribute.
