### ISSUE TITLE
Problem with the Markers

### ISSUE THREAD

**Issue by davidboutet** [yanwsh/videojs-panorama#116]
Cant add Markers in the config, forEach is undefined

MarkerGroup.js:29 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at new MarkerGroup (MarkerGroup.js:29)
    at new MarkerContainer (MarkerContainer.js:62)
    at b.handlePlay (Panorama.js:348)
    at HTMLDivElement.e (video.min.js:22)
    at HTMLDivElement.e (video.min.js:22)
    at HTMLDivElement.d.dispatcher.d.dispatcher (video.min.js:22)
    at Object.h [as trigger] (video.min.js:22)
    at b.a.trigger (video.min.js:14)
    at b.handleTechPlay_ (video.min.js:17)
    at b.e (video.min.js:22)

**Comment by yanwsh** [comment]
could you provide me your implementation code?

**Comment by yanwsh** [comment]
The input option for marker should be array.

like

`            Markers: [
                {
                    location: {
                        lat: 20,
                        lon: 160
                    },
                    radius: 500,
                    element: "Marker 2",
                }
            ]`

**Comment by davidboutet** [comment]
This is my configuration:
player.panorama({
                    clickToToggle: (!isMobile()),
                    clickAndDrag: true,
                    autoMobileOrientation: isMobile(),
                    initFov: 100,
                    VREnable: isMobile(),
                    backToInitLat: false,
                    backToInitLon: false,
                    Notice: {
                        Enabled: true,
                        Message: (isMobile())? "please drag and drop the video" : "please use your mouse drag and drop the video"
                    },
                    Markers: [
                        {
                            location: {
                                lat: 20,
                                lon: 160
                            },
                            radius: 500,
                            element: "Marker 2"
                        }
                    ],
                    ready: function () {
                        if(!isMobile()) player.play();
                    }
                });
and I still have the same issue "Cannot read property 'forEach' of undefined"

**Comment by yanwsh** [comment]
Thank you for your report, this bug is fixed, please [download](https://github.com/yanwsh/videojs-panorama/releases/tag/v1.0.0-beta) plugin again, and let me know if you have any other issues.

**Comment by davidboutet** [comment]
Everything is fine! Thanks
