### ISSUE TITLE
player.controlBar.getChild("VRButton") does not working in  beta version

### ISSUE THREAD

**Issue by ssalbal** [yanwsh/videojs-panorama#119]
VIDEOJS: ERROR: TypeError: Cannot read property 'handleClick' of undefined

player.on("play", function(){
     var vrbtn = player.controlBar.getChild("VRButton");
     vrbtn.handleClick();
});

Not beta version, it working.
Could you any comment?

**Comment by yanwsh** [comment]
Hey, this part of code embed in beta right now.  You can remove it safely.

**Comment by ssalbal** [comment]
thanks to your comment.
