### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by ruiluis** [yanwsh/videojs-panorama#122]
I tried to generate the videojs-panorama from source but i failed, downloaded the source from here(https://github.com/yanwsh/videojs-panorama/releases/tag/v1.0.0-beta)
then i did:
npm install --save-dev
gulp build
it said the version files were missing.. i then added the ones in the master
and it start complaining that it didnt found ./lib/canvas/

How do i compile it from source?

**Comment by yanwsh** [comment]
Yes, sorry for confuse. It should be gulp build-test, will fix this bug soon.

**Comment by ruiluis** [comment]
sorry.. big weekend..
i tried but "Task 'build-test' is not in your gulpfile"

------
Give a man a fish and you feed him for a day. Teach him how to fish and you
feed him for a lifetime.

**Comment by yanwsh** [comment]
Oh, my fault, it should be `gulp build-script-test`, if you want to develop, please run `gulp watch-test`

**Comment by ruiluis** [comment]
sorry for this.. its because i am using your plugin for some time and every
time you change i need to adapt my code to be compatible and alter the
production file and is becoming time consuming so i wanted to created the
necessary classes...

Starting 'build-script-test'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './videojs' from
... videojs-panorama-1.0.0-beta/src/scripts/tech'

------
Give a man a fish and you feed him for a day. Teach him how to fish and you
feed him for a lifetime.

**Comment by yanwsh** [comment]
make sure you have videojs.js file inside tech folder

**Comment by ruiluis** [comment]
sorry multi projects.. file in directory was with caps lock "Videojs.js" ..
changed and it start working.. thanks.

------
Give a man a fish and you feed him for a day. Teach him how to fish and you
feed him for a lifetime.
