### ISSUE TITLE
Auto Fullscreen in VRMode

### ISSUE THREAD

**Issue by Bjusters** [yanwsh/videojs-panorama#127]
Hey there,
it would be logical i think if clicking on the VRmode button automatically activates full screen. On desktop i got this to work by just listening in to the click and triggering a click on the fulscreen button. Mobile however is weird, i can only get it to work when adding an alert in a touchstart listener (weird "solution", i know) Is there a function i can call to force full screen when clicking on the VRMode button? Maybe it`s a nice feature to  automate this in a future version!

**Comment by yanwsh** [comment]
Hello, this is not possible for browser, because fullscreen need user interaction. 
But it can do fake fullscreen which is cover all the browser window. I think the beta version include this feature.

**Comment by Bjusters** [comment]
Cool, thank you, i`ll check out the Beta one of these days (was waiting for it to become production, look like it has many improvements!)
