### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by QuiqueScampini** [yanwsh/videojs-panorama#129]
Hi man, this is not an issue is like a question of how to use this. This is my situation:
I've got a dual fish eye stream from a ricoth thetha S and i'm trying to play that video on android... Just created a server with all the 4 steps you put in Readme, but i'm not undestanding the last part... Set up the video.js panorama plugin, 

player.panorama({
    clickAndDrag: true,
    callback: function () {
      player.play();
    }
});

Where should i put that part of the code???? 
My next question is, that server should be only a node server? Couldn't it be a tomcat or Flask with python? as far as i understood it's all javascript.

Thanks for your time

**Comment by yanwsh** [comment]
Hey, this is a front end code, which does not affect which backend server you use. 

but for node server if you use server side rendering, please make sure it's not running on backend because it should only be run on frontend side.

**Comment by QuiqueScampini** [comment]
Great, thanks for your help
