### ISSUE TITLE
Full screen with some videos doesn't work

### ISSUE THREAD

**Issue by harkenn** [yanwsh/videojs-panorama#17]
Most videos seem to be fine but others, such as this one:

http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

Do not engage in full screen. The fix on the main documentation doesn't work because there isn't a Canvas element underneath the Video, at least.

I've tried both v4 and v5 of the js in case there was something different between the two.

**Comment by yanwsh** [comment]
Hey, the video which you show me is not 360 video, I am not clear what's the use case you are using the 360 plugin. Could you provide me detail. Also, could you please provide me demo link if you can. Thank you.

**Comment by harkenn** [comment]
I'll open this one up on the videojs project, sorry for the confusion.
