### ISSUE TITLE
Any thoughts on how I might modify this to work within a React application?

### ISSUE THREAD

**Issue by ryandury** [yanwsh/videojs-panorama#18]
Hey there, i'm trying to get this to work inside of a react application. I believe where it's failing is actually with the reference to the three.js library. Any insight would be appreciated!

**Comment by ryandury** [comment]
Update, the video appears to load (I hear audio..) but the page is completely blank.

**Comment by yanwsh** [comment]
Hey, could you provide a demo for me to test?

**Comment by yanwsh** [comment]
I know react load script async. So you have to make sure three.js, videojs and videojs-panorama loaded before you call it out.  Did you see any error message on console?

**Comment by yanwsh** [comment]
Hello @ryandury, this is supported, please check #22 for reference.
