### ISSUE TITLE
Ios 10 support comming soon?

### ISSUE THREAD

**Issue by KevinBorghmans** [yanwsh/videojs-panorama#19]
Hey is there a IOS 10 support comming soon.
I tested the video on IOS 10 it works but it runs jagged.
could there be a fix or something to resolve this ?

-Thanks for the work already because it works perfect for the rest of the browsers that i need to use !

**Comment by yanwsh** [comment]
Hey, did you view 360 video on cellular network? It's a known issue that its run jagged because of the big video.

**Comment by KevinBorghmans** [comment]
Yes but also on Wifi. The video itself is 233MB for like 30m of video time. So that is ok I compressed it but kept a good quality. 

The thing is I tested it on multiple devices so on web browsers, IOS 9 and multiple android devices. Only a IOS 10 device is running the video jagged. The rest run silky smooth, so I don't know what i could do to fix it.

**Comment by zang** [comment]
It seems work fine for me on ios.

**Comment by yanwsh** [comment]
Hello, @KevinBorghmans , could you send your video file to me?

I think i found the issue and need to test it.

**Comment by KevinBorghmans** [comment]
@yanwsh  heya Yanwsh, i think its fixed i have the latest update now from apple the 10.1.1 and it works now it was probebly on the IOS part, Thanks for the help and looking into this problem!

**Comment by yanwsh** [comment]
@KevinBorghmans  cool, please update the latest version of this plugin. IOS 10 support play video inline directly.  https://webkit.org/blog/6784/new-video-policies-for-ios/
