### ISSUE TITLE
Video does not resize proportionately in fullscreen

### ISSUE THREAD

**Issue by fndaru** [yanwsh/videojs-panorama#26]
The video appears stretched when moving from one orientation to another in fullscreen. Tested on Chrome on Android 5.1

**Comment by fndaru** [comment]
Closing because i completely missed that you pointed this out in your documentation: https://github.com/yanwsh/videojs-panorama#resize-problem

**Comment by yanwsh** [comment]
Cool, let me know if you need other help.
