### ISSUE TITLE
Js error with v4

### ISSUE THREAD

**Issue by zang** [yanwsh/videojs-panorama#3]
With v5, the plugin works fine so far. With v4, we got the following error of running the demo on Chrome:
videojs-panorama.v4.min.js:1 Uncaught TypeError: Cannot read property 'el' of undefined

**Comment by yanwsh** [comment]
Hey, could you provide the detail how can I reproduce this issue? Which browser did you find the issue? If you can setup a demo page for me to debug the issue will be much helpful. Thanks for interesting.

**Comment by zang** [comment]
Thanks @yanwsh and I will provide more details early next week. Cool plugin btw :)

**Comment by yanwsh** [comment]
Sure, thanks for interesting and let me know anything i can help.

**Comment by zang** [comment]
I used the html of your demo page and changed to v4 and got the above error. :) Let me know if you need more information pls.

**Comment by yanwsh** [comment]
Oh, I got the issue. You have to use develop version of videojs 4. You can download videojs 4 source code [here](https://github.com/videojs/video.js/releases/download/v4.12.15/video-js-4.12.15.zip).

I also updated my documentation and setup a [demo page](http://yanwsh.github.io/videojs-panorama/index_v4.html) for videojs 4. 

Let me know if you have any questions.

**Comment by zang** [comment]
thanks @yanwsh

**Comment by adamck** [comment]
@yanwsh Is there any fundamental reason this shouldn't work with the production-ready version of video.js?

**Comment by yanwsh** [comment]
Hello, it's a production version, just should be not minified. In videojs 4, the minified version rename the API name, but my plugin need some API calling, so we can't use minified version directly. But you can download the unminified version and minified on your end. If you really want to use production-ready version, you can use videojs 5.

Let me know if you have any questions.

**Comment by yanwsh** [comment]
@zang @adamck  I updated source code, you don't have to use develop version, you can use production version now, let me know if you have any questions.

**Comment by zang** [comment]
Thanks a lot @yanwsh , it works fine. :)
