### ISSUE TITLE
Enable Cardboard by Default

### ISSUE THREAD

**Issue by tibewww** [yanwsh/videojs-panorama#30]
Hi, Amazing and working like a charm !

One question, are we able to launche the video with the Cardboard mode enable by default ?

If yes, how ? And possible to only read the video only this way ?

Thanks a lot !

**Comment by edoreyes** [comment]
Hello, great job here. 

I have the same question. 

Thanks in advance, 

Eduardo

**Comment by yanwsh** [comment]
You can enable it by listen video play event,

```
        player.on("play", function(){
            var vrbtn = player.controlBar.getChild("VRButton");
            vrbtn.handleClick();
        });
```

**Comment by edoreyes** [comment]
Wow! You are the best. Exactly that I needed it.
