### ISSUE TITLE
Internet Explorer Support?

### ISSUE THREAD

**Issue by j-christopher** [yanwsh/videojs-panorama#37]
Does VideoJS-Panorama support any version of IE? Currently, IE11 returns the following error: "The media could not be loaded, either because the server or network failed or because the format is not supported." I have confirmed this same video works across other modern browsers. 

Thanks

**Comment by yanwsh** [comment]
It should works on IE 11. Looks like it complains about the video type. which video type did you use? I tested with mp4, and don't have issue on IE 11.

**Comment by j-christopher** [comment]
I used an mp4 as well. Is there a specific mp4 encoding we should use?

**Comment by yanwsh** [comment]
I only test with H.264 encoding. Do you have demo page which i can test?  It's working on my machine.

**Comment by j-christopher** [comment]
I found this was due to either using 4K or too high of FPS. Once I re-published the file to 1080p and 29.97FPS it worked on IE11. It would be helpful to know what the limits are for dimensions and FPS for each browser.
