### ISSUE TITLE
Publish to Bower.io?

### ISSUE THREAD

**Issue by rgbohner** [yanwsh/videojs-panorama#38]
Any thoughts on publishing this as a bower package as well as npm since it's front-end functionality?  

Of course ""videojs-panorama" : "https://github.com/yanwsh/videojs-panorama.git#<commit_hash>", will work in the bower.json but it would be nice to reference versions and auto update as needed

**Comment by yanwsh** [comment]
Hey, this is support, please run bower install videojs-panorama, let me know if you have any questions.
