### ISSUE TITLE
Hi!,is it support  mobile devices accelerometer for 360 motion

### ISSUE THREAD

**Issue by sportexholdings** [yanwsh/videojs-panorama#4]
Hi!, I love your 360 Degree panorama view plugin.
is this plugin support:
support mobile devices accelerometer for 360 motion. which i mean is- gyroscope sensor/gyroscope viewing.

I have runing some test regarding this:
Link: http://xaphanentertainment.com/update360/mathew.php
How do i enable that feature for mobile device.

and how do i get work with water mark or logo branded plugin..Tried many time.,not success yet.
Thanks,
Imesh

**Comment by yanwsh** [comment]
Hey, this feature is under branch 'feature/mobileorientation'. I am still QA it right now. I am very appreciate if you can help testing. 
You can download code here: https://github.com/yanwsh/videojs-panorama/tree/feature/mobile-orientation/dist

This feature is disabled by default, so you need to setup in your options like below:

player.panorama({
      autoMobileOrientation: true,
});

Let me know me if you have any questions.

Thanks for interesting this plugin.

**Comment by sportexholdings** [comment]
Hi!,Thanks..
I hope i put code right way.
Can you checked please!.

Link: http://xaphanentertainment.com/update360/mathew.php

also,my logo is not showing. can you tell me,if i miss something in my code.
many thanks!,
Imesh

**Comment by yanwsh** [comment]
Hello,
First of all, the code is not the newest one, could you download code here, https://github.com/yanwsh/videojs-panorama/blob/feature/mobile-orientation/dist/videojs-panorama.v5.js
it include the feature for mobile accelerometer.

Second, you declared videojs twice (check line 253 and line 298). please remove the the line between 294 - 306. And add following code after 274.

```js
			player.logobrand({
				//height: "32px",
				//width: "32px",
				image: "logo.png",
				destination: "http://www.google.com/"
			});
```

I tested it, it should be working.

Let me know if you have any questions.

**Comment by sportexholdings** [comment]
Hi!, yes.it's work fine...
Link:  http://xaphanentertainment.com/360-fixed/new-test.html
I figured out one thing: click and drag. Right not it moves too quickly. i do i speed up this in mobile specially. anyway..this is perfect plugin for 360 Degree videos.. also,i have one request from you.can you add support for cube map encoded video as well..
Kindly regards!,
Imesh

**Comment by yanwsh** [comment]
Hello, you can speed up by setup mobileVibrationValue property.

By default, it's 0.022 on ios device and 1 on android or other phone.

You can increase it by you own.

```js
function isIos() {
    return /iPhone|iPad|iPod/i.test(navigator.userAgent);
}

 player.logobrand({
       mobileVibrationValue: isIos()? 0.032 : 1.5
 });
```

**Comment by sportexholdings** [comment]
Ok!,Thanks! my friend.... but it still has issue with control bar showing in ios device,test with iphone 6 plus.... anyway thanks.

**Comment by yanwsh** [comment]
yes, control bar will be hide on ios mobile device. I am working on that, will let you know when it's done.

**Comment by sportexholdings** [comment]
Hi!,how are you? i hope you are doing great.
How do i enable google card board view.like eleVR web Player..

Link: https://github.com/hawksley/eleVR-Web-Player

it's just a request.if you can enable that function through your plugin.that would be great.
Regards!,
Imesh

**Comment by yanwsh** [comment]
Hello, I don't have any device to test it right now. However, someone let me add this feature, and I put my code on vr-support branch (https://github.com/yanwsh/videojs-panorama/tree/vr-support). Please follow the reference from here https://github.com/slawrence/videojs-vr and the code I attached
[vr.zip](https://github.com/yanwsh/videojs-panorama/files/332170/vr.zip).

They told me it works. Let me know your result. Thanks.

**Comment by sportexholdings** [comment]
hi!,sorry! for late response,will update you soon..

**Comment by sportexholdings** [comment]
Hi!,is there way to link you tube video for this.... without linking, mp4...basically,i want to link 360 degree video..,with side by side viewing like eleVR-Web-Player. want to make it web base.
Thanks!

**Comment by yanwsh** [comment]
Sorry, I am not sure what you mean "without linking mp4 video". eleVR-Web-Player is played based on mp4 file. so could you provide me more detail?

**Comment by sportexholdings** [comment]
hi!, what i mean  is linking youtube video directly.without linking mp4 or webm video

**Comment by sportexholdings** [comment]
in more details something like this:

 class="player_container">
        <video id="videojs-panorama-player" class="video-js vjs-default-skin" poster="assets/poster-2.jpg"  crossorigin="anonymous" controls>
            <source src="https://www.youtube.com/watch?v=Isxq9P8E504" type='youtube'>
        </video>

with side by side viewing facility.with similar to eleVR-Web-Player

**Comment by sportexholdings** [comment]
is that possible to link youtube video instead of mp4/webm video ?

**Comment by criabdala** [comment]
Hi!, can I use an hls streaming (.m3u8)??

**Comment by sportexholdings** [comment]
yes.it's possible... m3u8 is playlist

**Comment by yanwsh** [comment]
@sportexholdings No, you can't use youtube video because of cross domain issue. Maybe you can download youtube video on backend? If you check 360 video on youtube, you can see 360 video is not support on safari because of that issue.

**Comment by yanwsh** [comment]
@criabdala Yes, you can do that. 

add following code into you video tag.

```js
<source src="playlist.m3u8" type="application/x-mpegURL">
```

**Comment by sportexholdings** [comment]
Hi!,
Thanks for all the support,that you provide us..
I have tried video with 360 view here:
http://chative.com/ad/imesh/test/test.html
But it's not work..Can you tell me what is the issue..i can't see the video?

**Comment by yanwsh** [comment]
Hey, nothing wrong with your code. The problem i guess is the video. The video is too big, just 50 seconds video and its large than 300M. If you network is slow, its buffering at the backend. That's why you see the black screen. Considering to reduce the video quality should be fine. 

I also made a demo for you.  http://vip.e-measurement.net/test.html

I add some features based on your video, so please download and update the latest version of source code.

Let me know if you have any questions.

**Comment by mostafa-v** [comment]
videojs panorama and hls works fine for me in chrome, but in firefox, it shows black screen with sounds playing, and video may apear if i seek back. what is the problem?

**Comment by yanwsh** [comment]
@mostafa-v I will test it.
