### ISSUE TITLE
Black Screen in Chrome

### ISSUE THREAD

**Issue by newtocoding123** [yanwsh/videojs-panorama#42]
Hi!

Issue is pertaining to when using on my laptop. The video player works perfectly fine on Firefox, however, when on Chrome, it only shows a black screen but there's audio. I'm using video.js 5 (latest). I am using the latest Chrome as well. I'm using my own video in my computer, not off any server else well. I got all the codes off from your demo(http://yanwsh.github.io/videojs-panorama/) by viewing the source and implementing them. 

Any suggestions what I can do?

Thank you!

**Comment by yanwsh** [comment]
Hello, this is because browser don't support cross domain, did you use remote video? You have to download video.

**Comment by newtocoding123** [comment]
I did not use remote video. The video file is in my computer. I used the video from my computer, no need for any server/internet etc. Currently, i have the crossorigin "anonymous" line removed so it's a black screen but with audio. However, if i add the crossorigin "anonymous" line, it changes to media file not supported instead.

**Comment by yanwsh** [comment]
which video did you use? mp4? Could you send whole project files to me? My email address is yanwsh@gmail.com.

**Comment by yanwsh** [comment]
Did you directly open html file on browser or base on a server?

**Comment by newtocoding123** [comment]
Yes I used an .mp4 360 video I downloaded from Youtube. Alright I'll send u my whole project files now. 
I open directly on browser. I am not making use of any server at all.

**Comment by yanwsh** [comment]
Solved, close ticket.
