### ISSUE TITLE
Standalone library

### ISSUE THREAD

**Issue by rafa8626** [yanwsh/videojs-panorama#47]
Is there a way to use this plugin without having to use it with VideoJS? I'm interested on integrating it with a different video player

**Comment by billymcintosh** [comment]
I'm also looking to integrate with Kaltura.

**Comment by yanwsh** [comment]
Thank you, i will work on it and let you know when it's done.

**Comment by ron666** [comment]
Thanks @yanwsh I'd really like to integrate it with MediaElementJS. Please keep us posted

**Comment by ron666** [comment]
@yanwsh Any updates on this?

**Comment by rafa8626** [comment]
Any updates on this?

**Comment by yanwsh** [comment]
Hi, i am working on it. will let you know when it's finish. The library is hardly depends on videojs. Need time to do standalone.

**Comment by rafa8626** [comment]
Thanks for the update

**Comment by yanwsh** [comment]
This is supported on v1.0.0, please check [here](https://github.com/yanwsh/videojs-panorama/releases/tag/v1.0.0-beta)

**Comment by rafa8626** [comment]
Thank you very much I'll check this soon

**Comment by yanwsh** [comment]
Please check [here](https://github.com/yanwsh/videojs-panorama/blob/feature/standalone/index_mediaplayer.html) for reference. 

Sorry for delay. It's not a easy process. I have to rewrite everything.

**Comment by rafa8626** [comment]
Sorry it has taking me time to review it; just for starters, how do I obtain the `dist` and the `assets` folders that are indicated in your test file for MEJS?

**Comment by rafa8626** [comment]
Also, I'd recommend to use external sources in the tests, rather than using bower references. I'll create a pull request for this next week
