### ISSUE TITLE
3D support 

### ISSUE THREAD

**Issue by PawelM83** [yanwsh/videojs-panorama#49]
Hi Yan,

really great job.
Since videojs-panorama supports 3D now, is there a way to show only one (left or right / upper or lower) part of a 3D video? For those people, who have no 3D devices like VR headsets or 3D-TVs, so they can take part to enjoy 3D SBS or Over/Under videos on e.g. desktop browsers.

Best regards
Pawel

**Comment by yanwsh** [comment]
Hello, please download the latest version of this plugin, https://github.com/yanwsh/videojs-panorama/blob/master/index_3d.html

It solve your problem for only show one part by default.

Let me know if you have any questions.

**Comment by PawelM83** [comment]
Hi Yan,

Great job....thank you very much. It works as expected.

Best regards
Pawel
