### ISSUE TITLE
autoMobileOrientation support

### ISSUE THREAD

**Issue by zang** [yanwsh/videojs-panorama#5]
Can I ask what mobile phone does this feature support? I checked your demo page on my Galaxy S7 edge and the video doesn't move when I move my phone around. thanks again.

**Comment by zang** [comment]
I lied, the video moves slightly. e.g. I turn the phone 180 degree and the video moves about 5 degree roughly. Is that the expected behavior?

**Comment by yanwsh** [comment]
Hey, I am still testing this feature. Could you setup a demo page for me? 

You can speed up by setup mobileVibrationValue property.

By default, it's 0.022 on ios device and 1 on android or other phone.

It's possible to increase it by you own.

```js
function isIos() {
    return /iPhone|iPad|iPod/i.test(navigator.userAgent);
}

 player.panorama({
       mobileVibrationValue: isIos()? 0.032 : 1.5
 });
```

**Comment by zang** [comment]
Sure. May I have your email address and I will send you a demo page url later on this week.

**Comment by yanwsh** [comment]
yanwsh@gmail.com

**Comment by sportexholdings** [comment]
Hi!,It's work great on That run android 6 and ios 9(iphone 6plus).
but need to update the speed...

function isIos() {
    return /iPhone|iPad|iPod/i.test(navigator.userAgent);
}

 player.panorama({
       mobileVibrationValue: isIos()? 0.032 : 1.5
 });

i didn't found any issue in this plugin.. also, can managed the plugin parameters easily..
Great work...
