### ISSUE TITLE
The format is not supported

### ISSUE THREAD

**Issue by restart08** [yanwsh/videojs-panorama#50]
Hi, I am a rookie of videojs and this is my first time to try to use video-panorama.
I followed your steps and download the demo code, but I found the shark.mp4 and fisheye.mp4 cannot play on my local computer and even on server.
I printed the failed message: The media could not be loaded either because the server or network failed or because the format is not supported.
(you can see from here:  http://imgur.com/a/dTMy2)
Could you tell me how to solve it?

**Comment by yanwsh** [comment]
Hello, this is because i use git large file to save the files on repository. So the video inside repository is just a place holder.

You can download the video from here.

https://www.dropbox.com/s/6ket4tqvdz5des5/shark.mp4?dl=0
