### ISSUE TITLE
Zoom on mobile?

### ISSUE THREAD

**Issue by atlance01** [yanwsh/videojs-panorama#54]
I've got everything up and running inside an Ionic app. One thing I'd really like is the ability to pinch-and-zoom! Is there a way to do this?

I have `scrollable: true,` set but it only seems to affect the desktop.

**Comment by yanwsh** [comment]
Okay, will wok on it.

**Comment by atlance01** [comment]
@yanwsh Awesome!! I'll keep an eye out for it. Thanks for all of your hard work!

**Comment by atlance01** [comment]
@yanwsh any progress on this yet?

**Comment by yanwsh** [comment]
Sorry for late reply, this is supported on latest version of videojs-panorama. Please download the latest version, https://github.com/yanwsh/videojs-panorama/tree/master/dist,

let me know if you have any questions.

**Comment by slementin** [comment]
@yanwsh is this update live on npm aswell?

**Comment by yanwsh** [comment]
Yes

**Comment by atlance01** [comment]
@yanwsh just checked out the latest version! It works perfectly for me. Thanks so much for you hard work and responsiveness.
