### ISSUE TITLE
VR button doesn't exists. 

### ISSUE THREAD

**Issue by SabaTD** [yanwsh/videojs-panorama#59]
Hello, first thanks for great plugin. 

I installed it today, works well in normal condition, perfect on full screen too but i haven't VR on/off button in my control panel.  I checked VREnable is true everywhere, changing it to false didn't helped too.
Any ideas ? 

Edit : 
Tryed code bellow, still not working, couse i haven't button in control panel to get clicked onplay.event.

player.on("play", function(){
         var vrbtn = player.controlBar.getChild("VRButton");
         vrbtn.handleClick();
});

**Comment by SabaTD** [comment]
Solved problem, nvm. 
Thanks again for code :)

**Comment by jalowin** [comment]
How do you solved the problem? I need add a button or function that start the video in VR mode but if I try use your code the javascript return me "undefinied"

Thanks for all

Best regards
