### ISSUE TITLE
Touch event delay on control bar

### ISSUE THREAD

**Issue by atlance01** [yanwsh/videojs-panorama#61]
First off, I love what you've done with this plugin. It's near flawless!
However, when using it on a mobile device (iOS), I experience a delay in the touch event. When trying to click any of the buttons on the control bar - I must press and hold for about a second before the tap is registered. 

Is there a remedy for this?

**Comment by yanwsh** [comment]
Which ios device did you use? I only tested on iphone 6 and above.
