### ISSUE TITLE
Update event?

### ISSUE THREAD

**Issue by andy-mcdonald** [yanwsh/videojs-panorama#63]
H yanwsh,

I'm looking to build a compass UI element on top of the panorama video but cannot seem to find if there is any sort of `update` event that I could use to listen for changes to the current lat / lon.

I've looked through all the documentation and read through the code but cannot seem to find a list of all the events that get fired (aside from `VRModeOn`).

Any advice would be greatly appreciated!

**Comment by andy-mcdonald** [comment]
For what it's worth, I managed to hack something together that works for my needs. I basically just added the following line to the `handleMouseMove`* and handleMobileOrientation` methods of the `BaseCanvas`:

```this.player().trigger('update', {lat: this.lat, lon: this.lon})```

Thanks again for an excellent library!


\* _I am using the `clickAndDrag: true` option so the line of code was placed within the corresponding  part of the `if/else` block_

**Comment by yanwsh** [comment]
Hello, you don't have to hack the code, and i don't recommend to do that because it will lose the code updating.

If you want to get lat and lon, you can do something like below:

```javascript
        player.on("mousemove", function(){
            var canvas = player.getChild('Canvas');
            console.log("lat: " + canvas.lat + ", lon: " + canvas.lon);
        });
```

**Comment by andy-mcdonald** [comment]
Thanks for the quick response! Followed your advice and I have everything working correctly now (except for one thing which I will create a separate issue for).

**Comment by shawnzam** [comment]
This or any other `on` function do not seem to work with the 1.0.0 beta release.

**Comment by shawnzam** [comment]
It seems that you can not grab the canvas with 

```
var canvas = player.getChild('Canvas');
```
it returns undefined.

**Comment by shawnzam** [comment]
##javascript

```(function(window, videojs) {
    var player = window.player = videojs('videojs-panorama-player', {
      controls: false
    });
    player.on('ended', function() {
      // qcontext.enableNextButton();
    });
	  player.on("keydown", function(){
		  var canvas = player.getChild('Canvas');
		  console.log("lat: " + canvas.lat + ", lon: " + canvas.lon);
	  });
    var panorama = player.panorama({
      PanoramaThumbnail: true,
      KeyboardControl: true,
      MouseEnable: false,
      scrollable: false,
      clickToToggle: false,
      KeyboardMovingSpeed: {
        x: 10,
        y: 10
      },
      ready: function() {
        player.play();
      },

      Notice: {
        Enable: true,
        Message: "please use the W,A,S and D keys to move around the video."
      },
    });
```

##html

```
<div id="player_wrapper" class="player_wrapper">
  <div class="player_container">
   <video id="videojs-panorama-player" class="video-js vjs-default-skin" crossorigin="anonymous" controls>
            <source src="https://s3.amazonaws.com/mktg-it-app-scripts/panarama/shark.mp4" type='video/mp4'>
        </video>
  </div>
 </div>
```

##Header

```<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r76/three.js"></script>
<script src="https://vjs.zencdn.net/6.4.0/video.js"></script>
<script src="https://s3.amazonaws.com/mktg-it-app-scripts/panarama/videojs-panorama.js"></script>
<link href="https://vjs.zencdn.net/6.4.0/video-js.css" rel="stylesheet" />
<link href="https://s3.amazonaws.com/mktg-it-app-scripts/panarama/videojs-panorama.css" rel="stylesheet" />```
