### ISSUE TITLE
Get currentTime

### ISSUE THREAD

**Issue by emomooney** [yanwsh/videojs-panorama#71]
Hi. 

Is there anyway to get the currentTime of the video playback? and also play, paused and ended states.

**Comment by yanwsh** [comment]
```javascript
//get current time
player.on("timeupdate", function(){
   var currentTime = Math.round(this.currentTime());
});
//on video play
player.on("play", function(){
});
//on video end
player.on("end", function(){
});
//video pause
player.on("pause",function(){
});
```

for detail, please check [videojs documentation](http://docs.videojs.com/).

**Comment by emomooney** [comment]
Thanks for that. I was sure I tried this but must have not done it correctly.
