### ISSUE TITLE
(Request/Question) Keyboard support

### ISSUE THREAD

**Issue by filipdanic** [yanwsh/videojs-panorama#77]
Greetings!

Love the plugin, but I’d really appreciate keyboard support. I’ve gone through the docs/issues and it seems this currently does not exist?

Is there any way to add this right now? If not, do you have any tips on how I could implement it as a core part of this plugin?

Thanks for the all the great work!

**Comment by yanwsh** [comment]
This is supported on v1.0.0, please check [here](https://github.com/yanwsh/videojs-panorama/releases/tag/v1.0.0-beta)
