### ISSUE TITLE
How to add next video button or previous video button.

### ISSUE THREAD

**Issue by rugokeyi1989** [yanwsh/videojs-panorama#78]
I want to add next video button or previous video button into videojs-panaoram. Would you please tell me how to add?

**Comment by yanwsh** [comment]
The easiest way to do it is to add "prev" and "next" button in html and position inside video player.

If you want to more elegant, you may consider to write videojs plugin to add button. Please check [here](https://github.com/yanwsh/videojs-panorama/blob/master/src/scripts/lib/VRButton.js) for example. Create a component and add it at runtime. 

You may also need to [video.js plugin](http://docs.videojs.com/tutorial-plugins.html) for detail.
