### ISSUE TITLE
iOS fullscreen

### ISSUE THREAD

**Issue by zang** [yanwsh/videojs-panorama#8]
The plugin works well on iOS, however if the viewer clicks on fullscreen button, the 360 feature disappears as it revert back to iOS native player. So, if there are way to override the fullscreen button to use canvas rather than the native player? :)

**Comment by yanwsh** [comment]
Hey, please pull the latest version of source code, then take at look [this page](https://github.com/yanwsh/videojs-panorama/blob/master/index.html) for reference. 

Let me know if you have any questions.

**Comment by zang** [comment]
Great and I will check out and keep you posted. Thanks.

**Comment by zang** [comment]
Great and I will check out and keep you posted. Thanks.
