### ISSUE TITLE
script for orientation reset to default (mobile and desktop)

### ISSUE THREAD

**Issue by quintenm** [yanwsh/videojs-panorama#83]
I have 2 pages, the video page (with panorama) and a page with video-controll buttons (play/pause/rewind/restart/orientation reset) — connected via Socket.io — what code can I use, so the orientation in a videojs panorama video wil be reseted (animate to) to the default orientation (mobile and desktop).

The second page, is made so i can remotly play/pause/... a video on a phone that's placed in a VR-headset.

**Comment by yanwsh** [comment]
Hello, please check [iframe](https://github.com/yanwsh/videojs-panorama/blob/master/iframe.html) and [iframe-video](https://github.com/yanwsh/videojs-panorama/blob/master/iframe-video.html) code for detail.

It use post message, but you can use any data like web socket to control.

**Comment by quintenm** [comment]
Can't find the the variables to send trought the function, could you give somme tips.
`player.contentWindow.postMessage({type: "device-motion", events: obj}, "*");`

the connection with the socket library, works
for example, i can control fullscreen/play/pause)

see my online demo [controlpannel](https://bapquintenmares.herokuapp.com/video/) and [video page](https://bapquintenmares.herokuapp.com/video/control.html)
(function will be called in socket.js)
