### ISSUE TITLE
Return to vert/horiz center programmatically

### ISSUE THREAD

**Issue by icetronics** [yanwsh/videojs-panorama#85]
Hi,
Thanks for this awesome plugin!
Could you please help me how is it possible to return to the initial lat/lon from outside? (e.g. I would put a button on the player so the user can reset their orientation)
Thanks a lot in advance.

**Comment by quintenm** [comment]
+1 I will follow this thread, I opened also a issue with same question, in combination with socket io. So I can fully control the video on other devices.

**Comment by yanwsh** [comment]
```javascript
var canvas = player.getChild('Canvas');
canvas.lat
canvas.lon
```

**Comment by icetronics** [comment]
Works great, thanks, @yanwsh! Is there a possibility to make this reset animated?

**Comment by icetronics** [comment]
I see your comment: https://github.com/yanwsh/videojs-panorama/issues/52#issuecomment-277162947
Is there an update when this could be expected? Or some thoughts on it how one could achieve it? Thanks!
