### ISSUE TITLE
Amazon S3 with Iphone issue - only sound

### ISSUE THREAD

**Issue by deanngo791** [yanwsh/videojs-panorama#86]
Hi,
Thanks for this awesome plugin!
I try to stream video from amazon s3. It works like a boss on desktop version, android mobile.
But issue appears when I play video on iphone (6, 6s+, 6s) both safari and chrome. I retrieve a black screen but video sound is still working.
- I tested with a video in same domain -> It works like a champ.
- I also config s3 bucket with CORS:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>origin</AllowedHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>http://*</AllowedOrigin>
    <AllowedOrigin>https://*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>origin</AllowedHeader>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
and Video player:
`<video  id="videojs-panorama-player" class="video-js vjs-default-skin"  crossOrigin="anonymous" controls>`
How can I  play video on iphone?
There are some issues I think it's related:
https://github.com/yanwsh/videojs-panorama/issues/14

Any better solutions?

**Comment by yanwsh** [comment]
Sorry, no, safari don't support cross domain. But you have two options to let it works.

First, you can use an iframe which hosted on amazon s3, which could solve cross domain issue. Please check example [iframe](https://github.com/yanwsh/videojs-panorama/blob/master/iframe.html) and [iframe-video](https://github.com/yanwsh/videojs-panorama/blob/master/iframe-video.html).

Second, you can set up proxy which fetch the resources from amazon s3. If you have self hosted server, you can set up proxy like `http://www.company.com/cdn/awesomevideo.mp4` -> `amazon s3/awesomevideo.mp4`. Which also keep the recourses on same domain.

**Comment by deanngo791** [comment]
Thanks for reply, Iframe is good solution.
Thanks for Awesome plugin.
