### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by longmen21** [yanwsh/videojs-panorama#9]
Hello, I'm trying to make the visual angles change directions automatically when people are watching the video. I hope to take use of the JS arrays to store a sequence of coordinates values of x/y/z axis, and let the visual angles switch by them.
For examples:
var coordinates = {(1,2,3),(2,3,4)}
How can I make it?
I've read your source code and found the snippet code "this.camera.lookat()".
Whether can I use it?

**Comment by yanwsh** [comment]
Here, this is the feature I am working on it right now, will let you know when it's done. Thank you.

**Comment by longmen21** [comment]
Thanks,man.I'm glad to hear that.Please notify me as soon as you make it. 👍

**Comment by yanwsh** [comment]
@longmen21 hello, please check the branch [feature/auto-moving](https://github.com/yanwsh/videojs-panorama/tree/feature/auto-moving)

basic idea is add following to settings, like

```javascript
           autoMoving: true,
            autoMovingTimeline: [
                {
                    keypoint: 1000,//when do you want animation happen
                    from: {
                        lon: -180,
                        lat: 0,
                    },
                    to:{
                        lon: -180 + -360,
                        lat: 0
                    },
                    duration: 5000,
                    ease: "linear",//support "linear", "easeInQuad", "easeOutQuad", "easeInOutQuad", you can do your own animation function by passing a function, you can check animation functions [here](http://gizma.com/easing/)
                    complete: function () { //fire when animation done.
                    }
                }
            ]
```

let me know if you have any questions or problems. I am still testing it right now.

**Comment by longmen21** [comment]
Thanks a lot, it's so wonderfullllll !!
