### ISSUE TITLE
rtmp live streaming support ?

### ISSUE THREAD

**Issue by pollylin914** [yanwsh/videojs-panorama#93]
Hi,

I'd like to use videojs-panorama to play live streaming.
I already to success apply on type="video/webm" but
when i changed to type="rtmp/flv" that will get the following errors.

```
TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.
    at Object.texImage2D (three.js:18909)
    at uploadTexture (three.js:17795)
    at WebGLTextures.setTexture2D (three.js:17473)
    at WebGLRenderer.setTexture2D (three.js:21851)
    at SingleUniform.setValueT1 [as setValue] (three.js:4515)
    at Function.WebGLUniforms.upload (three.js:4842)
    at setProgram (three.js:21300)
    at WebGLRenderer.renderBufferDirect (three.js:20047)
    at renderObjects (three.js:20872)
    at WebGLRenderer.render (three.js:20609)
```

May I kown that videojs-panorama can support rtmp live stream or not, 
if yes, how to use in react ?
Thank you~~

**Comment by yanwsh** [comment]
Could you send me a demo video to test it? i am not sure does it support it or not.

Thank you

yanwsh@gmail.com

**Comment by Jasonzn** [comment]
Anything update about this problem?
I try to play rtmp source to videojs-panorama, but it always shows "no video" error messages.

Just like: 
Player.src({ type: "rtmp/mp4", src: rtmp://..../xxx.mp4 });
Player.play();

Does it support rtmp protocol video playing?
Thank you so much.

Jason

**Comment by yanwsh** [comment]
After doing research, this is impossible. RTMP protocol don't support HTML5 video and should use legacy flash player to play.  Please consider to use m3u8 or other live stream which support HTML5 video.

**Comment by Jasonzn** [comment]
I know HTML5 don't support RTMP protocol, but VideoJS can do that.
I've tested RTMP streaming playback via Videojs flash player.

The videojs-panorama project is based on Videojs plug-in, so I misunderstand videojs-panorama can do that, too.

**Comment by yanwsh** [comment]
Flash player was blocked by main stream browsers by default. So user won't see video player if they don't setup permission properly.  I strongly recommend you to upgrade to HTML player.

**Comment by mudin** [comment]
@Jasonzn  did you make this work?

**Comment by Jasonzn** [comment]
> @Jasonzn did you make this work?

No, I didn't make it work. And that test project was ended.
Sorry I can't help you.

**Comment by joshhoegen-natgeo** [comment]
@imudin and @Jasonzn, I ended up using videojs-vr (there are some issues with a recent fiasco with file-stream, but it works when replacing the nested dep)
