### ISSUE TITLE
HLS on iOS Safari not working when when stream is set on videoElement.src

### ISSUE THREAD

**Issue by Hyddan** [yanwsh/videojs-panorama#95]
The presence of an HLS stream on iOS Safari is only checked against child source elements, not the videoElements src property.

This repo is currently over the data quota, I had to delete some files in my fork just to be able to clone it so I don't want to open a PR with these deletions but you can see what I did here to make it work in this case:
https://github.com/Hyddan/videojs-panorama/commit/06b43a23731e598e16ab17135a6fcd7be8af3266

**Comment by yanwsh** [comment]
Thank you so much, updated.
